# https://www.keycloak.org/server/containers
# 26.1.3
FROM quay.io/keycloak/keycloak:latest AS builder 

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure a database vendor
ENV KC_DB=postgres

WORKDIR /opt/keycloak
# for demonstration purposes only, please make sure to use proper certificates in production instead
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/ /opt/keycloak/

# change these values to point to a running postgres instance
ENV KC_DB=postgres
ENV KC_DB_URL=<DBURL>
ENV KC_DB_USERNAME=<DBUSERNAME>
ENV KC_DB_PASSWORD=<DBPASSWORD>
ENV KC_HOSTNAME=localhost
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]

# docker build . -t mykeycloak

# Keycloak in development mode (strictly avoided in production environments because it has insecure defaults)
# docker run --name mykeycloak -p 8080:8080 \
#         -e KC_BOOTSTRAP_ADMIN_USERNAME=admin -e KC_BOOTSTRAP_ADMIN_PASSWORD=change_me \
#         quay.io/keycloak/keycloak:latest \
#         start-dev

# Starting the optimized Keycloak container image
# docker run --name mykeycloak -p 8443:8443 -p 9000:9000 \
#         -e KC_BOOTSTRAP_ADMIN_USERNAME=admin -e KC_BOOTSTRAP_ADMIN_PASSWORD=change_me \
#         mykeycloak \
#         start --optimized --hostname=localhost

# docker run --name mykeycloak -p 8080:8080 \
#         -e KC_BOOTSTRAP_ADMIN_USERNAME=admin -e KC_BOOTSTRAP_ADMIN_PASSWORD=change_me \
#         quay.io/keycloak/keycloak:latest \
#         start \
#         --db=postgres --features=token-exchange \
#         --db-url=<JDBC-URL> --db-username=<DB-USER> --db-password=<DB-PASSWORD> \
#         --https-key-store-file=<file> --https-key-store-password=<password>

# http://localhost:8080

# Keycloak starts in production mode, using only secured HTTPS communication, and is available on https://localhost:8443.
# Health check endpoints are available at https://localhost:9000/health, https://localhost:9000/health/ready and https://localhost:9000/health/live.
# Opening up https://localhost:9000/metrics leads to a page containing operational metrics that could be used by your monitoring solution

# Exposing the container to a different port
# docker run --name mykeycloak -p 3000:8443 \
#         -e KC_BOOTSTRAP_ADMIN_USERNAME=admin -e KC_BOOTSTRAP_ADMIN_PASSWORD=change_me \
#         mykeycloak \
#         start --optimized --hostname=https://localhost:3000


# Importing A Realm On Startup(only make sense to do in Dev mode)
# docker run --name keycloak_unoptimized -p 8080:8080 \
#         -e KC_BOOTSTRAP_ADMIN_USERNAME=admin -e KC_BOOTSTRAP_ADMIN_PASSWORD=change_me \
#         -v /path/to/realm/data:/opt/keycloak/data/import \
#         quay.io/keycloak/keycloak:latest \
#         start-dev --import-realm